### ISSUE TITLE
Decrption : Please Fix decryption

### ISSUE THREAD

**Issue by archie9211** [TeamWin/android_device_motorola_chef#2]
decryption is fixed in this repo :
https://github.com/Chef-Sprout/android_device_motorola_chef_twrp

**Comment by betaxab** [comment]
solved.

**Comment by Hasaber8** [comment]
> decryption is fixed in this repo :
> https://github.com/Chef-Sprout/android_device_motorola_chef_twrp

Close itttttttttttttt
@archie9211
